version: '3'
services:
  mongo-db:
    image: mongo:latest
    ports:
      - 27017:27017 #hostport:containerport
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root-admin
      - MONGO_INITDB_ROOT_PASSWORD=root-admin123
    networks:
      - mongo_network1.0
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=ally
      - ME_CONFIG_BASICAUTH_PASSWORD=ally123
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root-admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root-admin123
      - ME_CONFIG_MONGODB_SERVER=mongo-db
    depends_on:
      - mongo-db
    networks:
      - mongo_network1.0

  nodejs-app:
    build:
      context: ./nodejs-app
    ports:
      - 3000:3000 # hostport:containerport
    networks:
      - mongo_network1.0
    depends_on:
      - mongo-db
    environment:
      - MONGO_URI=mongodb://root-admin:root-admin123@mongo-db:27017

networks:
  mongo_network1.0:
    driver: bridge

volumes:
  mongo_data: